name: Build binaries

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # allows manual triggering from UI, CLI, or API

permissions:
  contents: write

jobs:
  build_operators:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: sudo apt install lld
    - run: ./scripts/build_dandelion.sh
    - name: upload operators
      shell: bash
      run: gh release upload operators build_dandelion/functions/plume_* --clobber
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_client:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: ./scripts/build_client.sh
    - name: upload client
      shell: bash
      run: gh release upload client build/plume/benchmarks/tpch/plume_bench --clobber
      env:
        GH_REPO: ${{ github.repository }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}